import type { Product, Category, HeroSlide, Advantage, GalleryImage, ContactInfo } from '../types';
import mianBgImage from '../assets/images/mianBg2.jpg';

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Столовые свечи',
    slug: 'stolovye',
    image: 'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=400&h=300&fit=crop',
    description: 'Классические столовые свечи для вашего дома',
    productCount: 24,
  },
  {
    id: 'cat-2',
    name: 'Церковные свечи',
    slug: 'cerkovnye',
    image: 'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=400&h=300&fit=crop',
    description: 'Свечи для храмов и церквей',
    productCount: 18,
  },
  {
    id: 'cat-3',
    name: 'Декоративные свечи',
    slug: 'dekorativnye',
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=400&h=300&fit=crop',
    description: 'Украшение интерьера и подарки',
    productCount: 32,
  },
  {
    id: 'cat-4',
    name: 'Ароматические свечи',
    slug: 'aromaticheskie',
    image: 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=400&h=300&fit=crop',
    description: 'Свечи с натуральными ароматами',
    productCount: 21,
  },
  {
    id: 'cat-5',
    name: 'Свечи для торта',
    slug: 'dlya-torta',
    image: 'https://images.unsplash.com/photo-1558636508-e0db3814bd1d?w=400&h=300&fit=crop',
    description: 'Праздничные свечи для тортов',
    productCount: 15,
  },
  {
    id: 'cat-6',
    name: 'Хозяйственные свечи',
    slug: 'hozyajstvennye',
    image: 'https://images.unsplash.com/photo-1608181831718-2501980cc520?w=400&h=300&fit=crop',
    description: 'Практичные свечи на каждый день',
    productCount: 12,
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    article: '0001',
    name: 'Свеча столовая классическая "Слоновая кость"',
    description: 'Элегантная столовая свеча цвета слоновой кости. Идеально подходит для сервировки стола и создания уютной атмосферы. Производится из высококачественного парафина с добавлением стеарина для равномерного горения.',
    price: 120,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 49, price: 120 },
      { minQuantity: 50, maxQuantity: 99, price: 105 },
      { minQuantity: 100, maxQuantity: 199, price: 95 },
      { minQuantity: 200, price: 85 },
    ],
    images: [
      'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1608181831718-2501980cc520?w=600&h=600&fit=crop',
    ],
    category: 'Столовые свечи',
    categoryId: 'cat-1',
    colors: ['Слоновая кость', 'Белый'],
    size: { height: '25 см', diameter: '2.2 см', label: 'Стандарт' },
    weight: '80 г',
    material: 'Парафин + стеарин',
    burnTime: '7-8 часов',
    inStock: true,
    isHit: true,
    isNew: false,
    createdAt: '2024-01-15',
  },
  {
    id: 'prod-2',
    article: '0002',
    name: 'Свеча ароматическая "Лаванда Прованса"',
    description: 'Натуральная ароматическая свеча с эфирным маслом лаванды. Создаёт расслабляющую атмосферу и наполняет комнату нежным цветочным ароматом. Идеальна для медитации и релаксации.',
    price: 450,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 19, price: 450 },
      { minQuantity: 20, maxQuantity: 49, price: 400 },
      { minQuantity: 50, maxQuantity: 99, price: 360 },
      { minQuantity: 100, price: 320 },
    ],
    images: [
      'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&h=600&fit=crop',
    ],
    category: 'Ароматические свечи',
    categoryId: 'cat-4',
    colors: ['Лавандовый', 'Фиолетовый'],
    size: { height: '10 см', diameter: '8 см', label: 'Средняя' },
    weight: '250 г',
    material: 'Соевый воск',
    burnTime: '30-35 часов',
    fragrance: 'Лаванда',
    inStock: true,
    isHit: true,
    isNew: true,
    createdAt: '2024-03-01',
  },
  {
    id: 'prod-3',
    article: '0003',
    name: 'Свеча декоративная "Золотая спираль"',
    description: 'Уникальная декоративная свеча в форме спирали с золотым напылением. Станет изысканным украшением вашего интерьера и прекрасным подарком.',
    price: 780,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 9, price: 780 },
      { minQuantity: 10, maxQuantity: 29, price: 700 },
      { minQuantity: 30, maxQuantity: 59, price: 640 },
      { minQuantity: 60, price: 560 },
    ],
    images: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&h=600&fit=crop',
    ],
    category: 'Декоративные свечи',
    categoryId: 'cat-3',
    colors: ['Золотой', 'Белый'],
    size: { height: '20 см', diameter: '6 см', label: 'Большая' },
    weight: '350 г',
    material: 'Пчелиный воск',
    burnTime: '25-30 часов',
    inStock: true,
    isHit: false,
    isNew: true,
    createdAt: '2024-04-10',
  },
  {
    id: 'prod-4',
    article: '0004',
    name: 'Свеча церковная восковая №3',
    description: 'Традиционная церковная свеча из натурального пчелиного воска. Горит ровно и долго, с лёгким медовым ароматом.',
    price: 35,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 99, price: 35 },
      { minQuantity: 100, maxQuantity: 299, price: 28 },
      { minQuantity: 300, maxQuantity: 599, price: 24 },
      { minQuantity: 600, price: 20 },
    ],
    images: [
      'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&h=600&fit=crop',
    ],
    category: 'Церковные свечи',
    categoryId: 'cat-2',
    colors: ['Натуральный воск', 'Жёлтый'],
    size: { height: '30 см', diameter: '1 см', label: 'Тонкая' },
    weight: '25 г',
    material: 'Пчелиный воск',
    burnTime: '1.5-2 часа',
    inStock: true,
    isHit: true,
    isNew: false,
    createdAt: '2023-06-20',
  },
  {
    id: 'prod-5',
    article: '0005',
    name: 'Свеча ароматическая "Ваниль и корица"',
    description: 'Тёплый и уютный аромат ванили с нотками корицы. Создаёт праздничное настроение и наполняет дом ощущением тепла.',
    price: 520,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 19, price: 520 },
      { minQuantity: 20, maxQuantity: 49, price: 460 },
      { minQuantity: 50, maxQuantity: 99, price: 420 },
      { minQuantity: 100, price: 380 },
    ],
    images: [
      'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&h=600&fit=crop',
    ],
    category: 'Ароматические свечи',
    categoryId: 'cat-4',
    colors: ['Кремовый', 'Коричневый'],
    size: { height: '12 см', diameter: '9 см', label: 'Большая' },
    weight: '300 г',
    material: 'Соевый воск + кокосовый воск',
    burnTime: '40-45 часов',
    fragrance: 'Ваниль и корица',
    inStock: true,
    isHit: true,
    isNew: false,
    createdAt: '2024-01-05',
  },
  {
    id: 'prod-6',
    article: '0006',
    name: 'Свеча столовая витая "Бордо"',
    description: 'Витая столовая свеча насыщенного бордового цвета. Придаст особый шарм праздничной сервировке стола.',
    price: 180,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 29, price: 180 },
      { minQuantity: 30, maxQuantity: 59, price: 160 },
      { minQuantity: 60, maxQuantity: 99, price: 145 },
      { minQuantity: 100, price: 130 },
    ],
    images: [
      'https://images.unsplash.com/photo-1608181831718-2501980cc520?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&h=600&fit=crop',
    ],
    category: 'Столовые свечи',
    categoryId: 'cat-1',
    colors: ['Бордовый', 'Красный'],
    size: { height: '28 см', diameter: '2.5 см', label: 'Стандарт' },
    weight: '100 г',
    material: 'Парафин + стеарин',
    burnTime: '8-9 часов',
    inStock: true,
    isHit: false,
    isNew: true,
    createdAt: '2024-05-01',
  },
  {
    id: 'prod-7',
    article: '0007',
    name: 'Набор свечей для торта "Радуга"',
    description: 'Яркий набор из 24 свечей разных цветов для украшения торта. Безопасные, не оставляют следов на глазури.',
    price: 150,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 49, price: 150 },
      { minQuantity: 50, maxQuantity: 99, price: 130 },
      { minQuantity: 100, maxQuantity: 199, price: 110 },
      { minQuantity: 200, price: 95 },
    ],
    images: [
      'https://images.unsplash.com/photo-1558636508-e0db3814bd1d?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&h=600&fit=crop',
    ],
    category: 'Свечи для торта',
    categoryId: 'cat-5',
    colors: ['Разноцветный'],
    size: { height: '6 см', diameter: '0.5 см', label: 'Мини' },
    weight: '50 г',
    material: 'Парафин',
    burnTime: '10-15 минут',
    inStock: true,
    isHit: true,
    isNew: false,
    createdAt: '2023-09-12',
  },
  {
    id: 'prod-8',
    article: '0008',
    name: 'Свеча хозяйственная белая',
    description: 'Надёжная хозяйственная свеча для бытовых нужд. Долгое и стабильное горение, экономичный расход.',
    price: 25,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 199, price: 25 },
      { minQuantity: 200, maxQuantity: 499, price: 20 },
      { minQuantity: 500, maxQuantity: 999, price: 17 },
      { minQuantity: 1000, price: 14 },
    ],
    images: [
      'https://images.unsplash.com/photo-1608181831718-2501980cc520?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=600&h=600&fit=crop',
    ],
    category: 'Хозяйственные свечи',
    categoryId: 'cat-6',
    colors: ['Белый'],
    size: { height: '20 см', diameter: '2 см', label: 'Стандарт' },
    weight: '70 г',
    material: 'Парафин',
    burnTime: '6-7 часов',
    inStock: true,
    isHit: false,
    isNew: false,
    createdAt: '2023-03-10',
  },
  {
    id: 'prod-9',
    article: '0009',
    name: 'Свеча декоративная "Шар" матовая',
    description: 'Круглая декоративная свеча с матовой поверхностью. Отлично смотрится в композициях и как самостоятельный элемент декора.',
    price: 350,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 14, price: 350 },
      { minQuantity: 15, maxQuantity: 39, price: 310 },
      { minQuantity: 40, maxQuantity: 79, price: 280 },
      { minQuantity: 80, price: 250 },
    ],
    images: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&h=600&fit=crop',
    ],
    category: 'Декоративные свечи',
    categoryId: 'cat-3',
    colors: ['Серый', 'Бежевый', 'Белый'],
    size: { height: '10 см', diameter: '10 см', label: 'Средняя' },
    weight: '400 г',
    material: 'Парафин + стеарин',
    burnTime: '35-40 часов',
    inStock: true,
    isHit: false,
    isNew: false,
    createdAt: '2024-02-14',
  },
  {
    id: 'prod-10',
    article: '0010',
    name: 'Свеча ароматическая "Морской бриз"',
    description: 'Свежий морской аромат с нотками солёного ветра и водорослей. Переносит вас на берег океана.',
    price: 480,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 19, price: 480 },
      { minQuantity: 20, maxQuantity: 49, price: 430 },
      { minQuantity: 50, maxQuantity: 99, price: 385 },
      { minQuantity: 100, price: 340 },
    ],
    images: [
      'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1608181831718-2501980cc520?w=600&h=600&fit=crop',
    ],
    category: 'Ароматические свечи',
    categoryId: 'cat-4',
    colors: ['Голубой', 'Синий'],
    size: { height: '9 см', diameter: '8 см', label: 'Средняя' },
    weight: '220 г',
    material: 'Соевый воск',
    burnTime: '28-32 часа',
    fragrance: 'Морской бриз',
    inStock: true,
    isHit: false,
    isNew: true,
    createdAt: '2024-05-20',
  },
  {
    id: 'prod-11',
    article: '0011',
    name: 'Свеча столовая "Пудровая роза"',
    description: 'Нежная столовая свеча в пудровом оттенке розового. Создаёт романтическую атмосферу для особых вечеров.',
    price: 160,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 39, price: 160 },
      { minQuantity: 40, maxQuantity: 79, price: 140 },
      { minQuantity: 80, maxQuantity: 149, price: 125 },
      { minQuantity: 150, price: 110 },
    ],
    images: [
      'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&h=600&fit=crop',
    ],
    category: 'Столовые свечи',
    categoryId: 'cat-1',
    colors: ['Розовый', 'Пудровый'],
    size: { height: '25 см', diameter: '2.2 см', label: 'Стандарт' },
    weight: '80 г',
    material: 'Парафин + стеарин',
    burnTime: '7-8 часов',
    inStock: true,
    isHit: false,
    isNew: false,
    createdAt: '2024-02-01',
  },
  {
    id: 'prod-12',
    article: '0012',
    name: 'Свеча декоративная "Колонна" рустик',
    description: 'Массивная декоративная свеча в рустикальном стиле с текстурной поверхностью. Идеальна для создания атмосферы загородного дома.',
    price: 650,
    wholesaleTiers: [
      { minQuantity: 1, maxQuantity: 9, price: 650 },
      { minQuantity: 10, maxQuantity: 29, price: 580 },
      { minQuantity: 30, maxQuantity: 59, price: 520 },
      { minQuantity: 60, price: 470 },
    ],
    images: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1608181831718-2501980cc520?w=600&h=600&fit=crop',
    ],
    category: 'Декоративные свечи',
    categoryId: 'cat-3',
    colors: ['Бежевый', 'Песочный'],
    size: { height: '18 см', diameter: '7 см', label: 'Большая' },
    weight: '500 г',
    material: 'Парафин + пчелиный воск',
    burnTime: '50-60 часов',
    inStock: true,
    isHit: true,
    isNew: false,
    createdAt: '2023-11-05',
  },
];

export const heroSlides: HeroSlide[] = [
  {
    id: 'slide-1',
    title: 'Профессиональные решения в мире свечей',
    subtitle: 'Оптовые цены, лучшее качество, доставка в ваш город в кротчайшие сроки.',
    image: mianBgImage,
    buttonText: 'Смотреть каталог',
    buttonLink: '/catalog',
  },
  // {
  //   id: 'slide-2',
  //   title: 'Оптовые поставки',
  //   subtitle: 'Специальные цены для оптовых покупателей. Свечи для храмов, магазинов и событий',
  //   image: 'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=1400&h=600&fit=crop',
  //   buttonText: 'Узнать условия',
  //   buttonLink: '/clients/cooperation',
  // },
  // {
  //   id: 'slide-3',
  //   title: 'Ароматерапия',
  //   subtitle: 'Натуральные ароматические свечи для релаксации и хорошего настроения',
  //   image: 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=1400&h=600&fit=crop',
  //   buttonText: 'Выбрать аромат',
  //   buttonLink: '/catalog?category=cat-4',
  // },
];

export const advantages: Advantage[] = [
  {
    id: 'adv-1',
    icon: 'leaf',
    title: 'Натуральные материалы',
    description: 'Используем только качественное сырьё: пчелиный воск, соевый воск, парафин высшего сорта',
  },
  {
    id: 'adv-2',
    icon: 'truck',
    title: 'Доставка по всей России',
    description: 'Отправляем заказы в любой город. Бережная упаковка для хрупких товаров',
  },
  {
    id: 'adv-3',
    icon: 'wholesale',
    title: 'Цены и опт',
    description: 'Специальные цены для оптовых покупателей. Гибкая система скидок',
  },
  {
    id: 'adv-4',
    icon: 'quality',
    title: 'Гарантия качества',
    description: 'Каждая свеча проходит контроль качества. Более 10 лет на рынке',
  },
];

export const galleryImages: GalleryImage[] = [
  { id: 'gal-1', src: 'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&h=400&fit=crop', alt: 'Столовые свечи в интерьере', category: 'Интерьер' },
  { id: 'gal-2', src: 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&h=400&fit=crop', alt: 'Ароматические свечи', category: 'Продукция' },
  { id: 'gal-3', src: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&h=400&fit=crop', alt: 'Декоративные свечи', category: 'Продукция' },
  { id: 'gal-4', src: 'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=600&h=400&fit=crop', alt: 'Церковные свечи', category: 'Продукция' },
  { id: 'gal-5', src: 'https://images.unsplash.com/photo-1608181831718-2501980cc520?w=600&h=600&fit=crop', alt: 'Свечи ручной работы', category: 'Производство' },
  { id: 'gal-6', src: 'https://images.unsplash.com/photo-1558636508-e0db3814bd1d?w=600&h=400&fit=crop', alt: 'Праздничные свечи', category: 'Праздники' },
  { id: 'gal-7', src: 'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&h=600&fit=crop', alt: 'Свечи для мероприятий', category: 'Мероприятия' },
  { id: 'gal-8', src: 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&h=600&fit=crop', alt: 'Уютная атмосфера', category: 'Интерьер' },
];

export const contactInfo: ContactInfo = {
  phone: '+7 (800) 123-45-67',
  email: 'info@mirsvchi.ru',
  address: 'г. Москва, ул. Примерная, д. 1, офис 101',
  workingHours: 'Пн-Пт: 9:00 - 18:00, Сб: 10:00 - 15:00',
  socialLinks: {
    telegram: 'https://t.me/mirsvchi',
    whatsapp: 'https://wa.me/78001234567',
    vk: 'https://vk.com/mirsvchi',
  },
};

export const availableColors: string[] = [
  'Белый', 'Слоновая кость', 'Кремовый', 'Бежевый', 'Песочный',
  'Золотой', 'Розовый', 'Пудровый', 'Лавандовый', 'Фиолетовый',
  'Голубой', 'Синий', 'Бордовый', 'Красный', 'Коричневый',
  'Серый', 'Натуральный воск', 'Жёлтый', 'Разноцветный',
];

export const availableSizes: string[] = ['Мини', 'Тонкая', 'Стандарт', 'Средняя', 'Большая'];
